name: 'Git commit'

description: 'Git commit'

inputs:
  message:
    description: 'Commit messsage'
    required: true
  repo_dir:
    description: 'Directory to add & commit'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure GIT
      shell: bash
      run: |
        git config --global user.email "bot@raycast.com"
        git config --global user.name "raycastbot"
    - name: Commit
      shell: bash
      working-directory: ${{ inputs.repo_dir }}
      run: |
        if ! [[ -z $(git status -s) ]] ; then
          git add .
          git status .
          git commit --message "${{ inputs.message }}"
          git push -u origin HEAD
        else
          echo "No changes, skipping sync."
        fi