name: 'Setup Raycast CLI'

description: 'Setup Raycast CLI'

inputs:
  access_token:
    description: 'Access Token'
    required: true
  api_url:
    description: 'API url'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create config
      shell: bash
      run: |
        path=~/.config/raycast-debug
        mkdir -p $path
        config_file_path=$path/config.json
        jq -n --arg accesstoken "${{ inputs.access_token }}" --arg apiurl "${{ inputs.api_url }}" '{"accesstoken": $accesstoken, "apiurl": $apiurl}' > $config_file_path
    - name: Download ray CLI
      shell: bash
      run: |
        wget -q -O "/usr/local/bin/ray" "https://raycast-cli.s3.eu-central-1.amazonaws.com/linux/ray"
        wait
        chmod +x "/usr/local/bin/ray"
        ray version